databases:
    tag_postgresql: # Unique tag
        engine: postgresql # Engine name (`postgresql` pr `mysql`)
        host: localhost # Database host
        port: 5432 # Database port
        user: db_user # Username
        password: db_password # Optional password
        db: my_db_functional_test # Database name
        # sslmode: require
        # sslcert: /path/to/client-cert.pem
        # sslkey: /path/to/client-key.pem
        # sslrootcert: /etc/ssl/certs/your-ca-cert.pem
        # sslcrl: /etc/ssl/certs/crl.pem # Optional SSL certificate revocation list
        sslcompression: 1
        path: src/unittest/utils/migrations_functional_test/postgresql/ # Path to the migration folder
        pre_migration: 'SELECT 1;' # Optional queries ran before migrating
        post_migration: 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres; GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres' # Optional queries ran after migrating
    tag_mysql:
        engine: mysql
        host: localhost
        port: 3306
        user: root
        password: root
        db: my_db_functional_test
        # ssl_check_hostname: true # set to false to disable hostname checking of the server cert
        # ssl_cert: /path/to/client-cert.pem
        # ssl_key: /path/to/client-key.pem
        # ssl_ca: /etc/ssl/certs/your-ca-cert.pem
        # ssl_cipher: 'cipher-name'
        # ssl_capath: /path/to/ca-certs/
        path: src/unittest/utils/migrations_functional_test/mysql/

